In [2]:
import numpy as np
import pandas as pd

In [3]:
dados = np.fromfile('rna-2025.1-pp2.1-dados/dataAll.txt')
dados


array([-363.7884,  244.1423,    0.    , ..., -140.147 ,  734.0983,
          0.    ], shape=(3000,))

In [4]:
m = dados.size//3
dados = dados.reshape((m,1,3))
print(dados.shape)
print(dados.dtype)

(1000, 1, 3)
float64


In [5]:
dados

array([[[-363.7884,  244.1423,    0.    ]],

       [[ 328.7572, -256.7658,    1.    ]],

       [[-164.9827,  613.2164,    0.    ]],

       ...,

       [[ 872.4311,  669.1192,    1.    ]],

       [[ 822.6894, -702.6489,    1.    ]],

       [[-140.147 ,  734.0983,    0.    ]]], shape=(1000, 1, 3))

In [6]:
X = np.array([[linha[0][0], linha[0][1]] for linha in dados])
y = np.array([[linha[0][2]] for linha in dados])

In [7]:
X

array([[-363.7884,  244.1423],
       [ 328.7572, -256.7658],
       [-164.9827,  613.2164],
       ...,
       [ 872.4311,  669.1192],
       [ 822.6894, -702.6489],
       [-140.147 ,  734.0983]], shape=(1000, 2))

In [8]:
y

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],

In [9]:
def step(x):
    return 1 if x >= 0 else 0

In [10]:
def check_error(y_predicted, y):
    if y_predicted != y:
        return True
    return False

In [11]:
class Perceptron:
    def __init__(self, learning_rate=0.1, epochs=100):
        self.learning_rate = learning_rate
        self.epochs = epochs
        self.weights = None
        self.bias = None
        self.necessary_epochs = None
        self.total_adjust = 0

    def fit(self, X, y):
        #n_samples, n_features = X.shape
        self.weights = (np.random.uniform(-0.5, 0.5), np.random.uniform(-0.5, 0.5))
        print("Pesos iniciais: ", self.weights)
        self.bias = 0
        self.necessary_epochs =0
        

        for _ in range(self.epochs):
            self.necessary_epochs +=1
            error_counter = 0
            for idx, x_i in enumerate(X):
                linear_output = np.dot(x_i, self.weights) + self.bias
                y_predicted = step(linear_output)
                print(y_predicted, y[idx], '   ')
                if(check_error(y_predicted, y[idx])):
                    
                    update = self.learning_rate * (y[idx] - y_predicted)
                    self.weights += update * x_i
                    self.bias += update
                    error_counter +=1
                    self.total_adjust+=1
                else:
                    pass
            if error_counter ==0:
                return
            print('\n')

    def predict(self, X):
        linear_output = np.dot(X, self.weights) + self.bias
        return step(linear_output)


In [12]:
perceptron = Perceptron()
perceptron.fit(X, y)


Pesos iniciais:  (0.27323716537434184, -0.1643214492160916)
0 [0.]    
1 [1.]    
0 [0.]    
1 [0.]    
0 [0.]    
1 [1.]    
1 [1.]    
0 [1.]    
1 [1.]    
1 [1.]    
1 [1.]    
0 [0.]    
0 [0.]    
0 [0.]    
1 [1.]    
0 [0.]    
0 [0.]    
0 [0.]    
0 [1.]    
1 [1.]    
1 [1.]    
0 [0.]    
0 [0.]    
0 [0.]    
0 [0.]    
0 [0.]    
1 [0.]    
1 [1.]    
1 [1.]    
0 [0.]    
1 [1.]    
1 [0.]    
1 [1.]    
1 [1.]    
1 [1.]    
1 [1.]    
1 [1.]    
1 [1.]    
1 [1.]    
0 [0.]    
0 [0.]    
1 [0.]    
1 [1.]    
0 [0.]    
1 [1.]    
0 [1.]    
0 [0.]    
1 [0.]    
1 [1.]    
1 [1.]    
1 [1.]    
1 [1.]    
0 [0.]    
1 [1.]    
0 [0.]    
1 [1.]    
1 [1.]    
1 [1.]    
0 [0.]    
0 [0.]    
0 [0.]    
1 [1.]    
1 [1.]    
1 [1.]    
1 [1.]    
0 [0.]    
0 [0.]    
0 [0.]    
1 [1.]    
0 [0.]    
1 [1.]    
0 [1.]    
1 [1.]    
1 [1.]    
0 [0.]    
1 [1.]    
0 [0.]    
1 [1.]    
1 [1.]    
0 [0.]    
0 [0.]    
0 [0.]    
1 [1.]    
0 [0.]    
0 [0.]    
1 [1.

In [13]:

# Fazendo previsões
predictions = [perceptron.predict(x) for x in X]
print(f"Predicoes: {predictions}")
print(f"\nEpocas necessarias: {perceptron.necessary_epochs}")
print(f"Total de ajuste de pesos: {perceptron.total_adjust}")


Predicoes: [0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0